[package]
name = "contact-form"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]] # double brackets mean array, we can have one lib but multiple binaries
path = "src/main.rs"
name = "contact_form"

[dependencies]
askama = "0.12.1"
askama_axum = "0.4.0"
axum = "0.7.5"
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["fs", "trace"] }
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "chrono", "migrate"] }
config = {version = "0.14", features = ["yaml"]}
uuid = { version = "1.9.1", features = ["v4"] }
tower = "0.4.13"
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-bunyan-formatter = "0.3.9"
chrono = "0.4.38"
secrecy = { version = "0.8", features = ["serde"] }
serde-aux = "4.5.0"
unicode-segmentation = "1.11.0"
validator = "0.18"

# [dev-dependencies]
# reqwest = { version = "0.12.4"}
# once_cell = { version = "1.19" }

[dev-dependencies]
# reqwest = { version = "0.12", features = ["json"] }
reqwest = { version = "0.12"}
claims = "0.7.0"
quickcheck = "1.0"
quickcheck_macros = "1.0"
fake = "2.9"
once_cell = "1.19.0"
rand = "0.8.5"