services:
  postgres:
    image: postgres:latest
    container_name: postgres-contact-form
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
