application:
  port: 8000
  host: 0.0.0.0
database:
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "testes@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000